apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-blue
  labels:
    app: myapp-deployment-blue
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        version: blue
    spec:
      containers:
        - name: myapp-container
          image: nginx:1.24.0
  replicas: 1
  selector:
    matchLabels:
      version: blue
      app: myapp
